---

- name: Include rootless user setup
  become: true
  ansible.builtin.import_role:
    name: philnewm.podman_rootless_user
  vars:
    rootless_user: "{{ caddy_user }}"
    rootless_user_home: "/var/lib/{{ caddy_user }}"
    system_user: true

- name: Ensure required podman packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present
    update_cache: true

- name: Include pulp setup
  ansible.builtin.include_tasks:
    file: service_setup.yml

- name: Configure firwalld
  become: true
  when: caddy_configure_firewalld
  block:
    - name: Ensure firewalld is installed
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      ansible.builtin.systemd_service:
        name: firewalld
        state: started
        enabled: true
        daemon_reload: true

    - name: Configure HTTP/HTTPS port forwarding
      loop:
        - port: "443"
          proto: tcp
          toport: "8443"
        - port: "80"
          proto: tcp
          toport: "8080"
      loop_control:
        label: "{{ item.port }}/{{ item.proto }} -> {{ item.toport }}"
      ansible.posix.firewalld:
        zone: public
        port_forward:
          - port: "{{ item.port }}"
            proto: "{{ item.proto }}"
            toport: "{{ item.toport }}"
        state: enabled
        permanent: true
        immediate: true

...
